#! /bin/sh
### BEGIN INIT INFO
# Provides:          Start s0-logger: Listen to trigger on GPIO and update values
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Kurze Beschreibung
# Description:       Längere Bechreibung
### END INIT INFO
# Initial version by Johannes Weber (johannes@webernetz.net)
# Author: Michael Eitelwein (michael@eitelwein.net)
 
# Aktionen
case "$1" in
    start)
        if ! [ -e /var/run/s0logger.pid ]; then
            /usr/bin/python /root/scripts/s0logger.py &
        else
            echo "s0logger is already running!"
        fi
        ;;
    stop)
        if [ -e /var/run/s0logger.pid ]; then
            pkill -F /var/run/s0logger.pid
        else
            echo "No instance of s0logger running!"
        fi
        ;;
    restart)
        if [ -e /var/run/s0logger.pid ]; then
            pkill -F /var/run/s0logger.pid
        fi
        sleep 2
        /usr/bin/python /root/scripts/s0logger.py &
        ;;
esac
 
exit 0
